

cache:
  image: redis

db:
  image: library/postgres
  volumes:
   - ./sql:/docker-entrypoint-initdb.d
  environment:
   - POSTGRES_PASSWORD=secret

host-server:
  image: thorium/host-server:latest
  ports:
   - "10000-60000"
  volumes:
   - /opt/thorium/gameserver:/opt/thorium/gameserver

master-server:
    build: ./cmd/masterserver
    ports:
     - "6960:6960"
    volumes:
     - .:/usr/src/app
    links:
        - cache
        - db

